name: fr_lenra_client
description: Plateforme d'applications dans le Cloud
publish_to: none
version: 0.1.0+alpha.0
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  intl: ^0.17.0
  # phoenix_wings: ^1.0.0
  phoenix_wings: 
    git:
      url: https://github.com/pichoemr/phoenix_wings.git
      ref: fix-nullsafety
  http: ^0.13.3
  sentry_flutter: ^5.1.0
  provider: ^5.0.0
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_launcher_icons: "^0.9.0"
  pedantic: ^1.11.0
  mockito: ^5.0.10
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
        - asset: fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
        - asset: fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf

flutter_icons: # see https://pub.dev/packages/flutter_launcher_icons
  image_path: "assets/images/icon-512.png"
  image_path_ios: "assets/images/icon-1024-white-bg.png"
  remove_alpha_ios: true
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/maskable-icon.png"
