name: Generate and Deploy Doc
on:
  push:
    branches:
      - beta

env:
  flutter_version: "3.0.x"

permissions:
  contents: write
jobs:
  generate-and-deploy-doc:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ env.flutter_version }}

      - name: Install and Build ğŸ”§
        run: dart doc .

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/api # The folder the action should deploy.
